name: Docker Publish (Production)

on:
  workflow_dispatch:
  release:
    types: [released]
  schedule:
    - cron: '0 8 * * 2'

jobs:

  build:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      tags: "serversideup/proftpd:latest,serversideup/proftpd:${{ github.ref_name }}"
    secrets: inherit