name: Workflow

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Analyze workflow files
        uses: docker://rhysd/actionlint:1.7.0
        with:
          args: "-color -verbose -shellcheck="
